,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,body,performed_via_github_app,pull_request
0,https://api.github.com/repos/pandas-dev/pandas/issues/43212,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43212/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43212/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43212/events,https://github.com/pandas-dev/pandas/issues/43212,979475977,MDU6SXNzdWU5Nzk0NzU5Nzc=,43212,BUG: MultiIndex.putmask,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],,1,2021-08-25T17:44:51Z,2021-08-25T18:08:20Z,,MEMBER,,"```
left = pd.MultiIndex.from_tuples([(np.nan, 6), (np.nan, 6), (""a"", 4)])
right = pd.MultiIndex.from_tuples([(""a"", 1), (""a"", 1), (""d"", 1)])
mask = np.array([True, True, False])

result = left.putmask(mask, right)
>>> result
[...]
IndexError: list index out of range
```

The result here somehow ended up with `len(result.levels) == 0`",,
1,https://api.github.com/repos/pandas-dev/pandas/issues/43211,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43211/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43211/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43211/events,https://github.com/pandas-dev/pandas/pull/43211,979126991,MDExOlB1bGxSZXF1ZXN0NzE5NTgzODky,43211,Bug resolve,"{'login': 'soni-muskan1234', 'id': 72978243, 'node_id': 'MDQ6VXNlcjcyOTc4MjQz', 'avatar_url': 'https://avatars.githubusercontent.com/u/72978243?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/soni-muskan1234', 'html_url': 'https://github.com/soni-muskan1234', 'followers_url': 'https://api.github.com/users/soni-muskan1234/followers', 'following_url': 'https://api.github.com/users/soni-muskan1234/following{/other_user}', 'gists_url': 'https://api.github.com/users/soni-muskan1234/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/soni-muskan1234/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/soni-muskan1234/subscriptions', 'organizations_url': 'https://api.github.com/users/soni-muskan1234/orgs', 'repos_url': 'https://api.github.com/users/soni-muskan1234/repos', 'events_url': 'https://api.github.com/users/soni-muskan1234/events{/privacy}', 'received_events_url': 'https://api.github.com/users/soni-muskan1234/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2021-08-25T13:05:54Z,2021-08-25T17:54:06Z,,NONE,,"
changed file generic.py and style.py
replaced if axis in [...] with get_axis_number(axis)
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43211', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43211', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43211.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43211.patch'}"
2,https://api.github.com/repos/pandas-dev/pandas/issues/43210,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43210/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43210/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43210/events,https://github.com/pandas-dev/pandas/pull/43210,979089593,MDExOlB1bGxSZXF1ZXN0NzE5NTU1NzM5,43210,TST: categorical reindex with added categories,"{'login': 'Sheogorath27', 'id': 8259394, 'node_id': 'MDQ6VXNlcjgyNTkzOTQ=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8259394?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/Sheogorath27', 'html_url': 'https://github.com/Sheogorath27', 'followers_url': 'https://api.github.com/users/Sheogorath27/followers', 'following_url': 'https://api.github.com/users/Sheogorath27/following{/other_user}', 'gists_url': 'https://api.github.com/users/Sheogorath27/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/Sheogorath27/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/Sheogorath27/subscriptions', 'organizations_url': 'https://api.github.com/users/Sheogorath27/orgs', 'repos_url': 'https://api.github.com/users/Sheogorath27/repos', 'events_url': 'https://api.github.com/users/Sheogorath27/events{/privacy}', 'received_events_url': 'https://api.github.com/users/Sheogorath27/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-25T12:29:47Z,2021-08-25T12:29:47Z,,NONE,,"- [x] closes #42424 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

The bug is specifically in the Interval index. The error arises in the example code from the issue while reindexing the categorical index with another categorical index(with new categories). 

The test (test_cut_with_nonexact_categorical_indices)  from PR [42425](https://github.com/pandas-dev/pandas/pull/42425) implicitly works in a similar way.
 
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43210', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43210', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43210.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43210.patch'}"
3,https://api.github.com/repos/pandas-dev/pandas/issues/43209,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43209/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43209/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43209/events,https://github.com/pandas-dev/pandas/issues/43209,979005022,MDU6SXNzdWU5NzkwMDUwMjI=,43209,BUG: groupby aggregation methods produce empty DataFrame with mixed DataTypes,"{'login': 'johanneselbs', 'id': 10251695, 'node_id': 'MDQ6VXNlcjEwMjUxNjk1', 'avatar_url': 'https://avatars.githubusercontent.com/u/10251695?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/johanneselbs', 'html_url': 'https://github.com/johanneselbs', 'followers_url': 'https://api.github.com/users/johanneselbs/followers', 'following_url': 'https://api.github.com/users/johanneselbs/following{/other_user}', 'gists_url': 'https://api.github.com/users/johanneselbs/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/johanneselbs/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/johanneselbs/subscriptions', 'organizations_url': 'https://api.github.com/users/johanneselbs/orgs', 'repos_url': 'https://api.github.com/users/johanneselbs/repos', 'events_url': 'https://api.github.com/users/johanneselbs/events{/privacy}', 'received_events_url': 'https://api.github.com/users/johanneselbs/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 71268330, 'node_id': 'MDU6TGFiZWw3MTI2ODMzMA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/MultiIndex', 'name': 'MultiIndex', 'color': '207de5', 'default': False, 'description': None}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform'}, {'id': 2365504383, 'node_id': 'MDU6TGFiZWwyMzY1NTA0Mzgz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reduction%20Operations', 'name': 'Reduction Operations', 'color': '547c03', 'default': False, 'description': 'sum, mean, min, max, etc.'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/89', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/89', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/89/labels', 'id': 7059576, 'node_id': 'MI_kwDOAA0YD84Aa7h4', 'number': 89, 'title': '1.3.3', 'description': 'on-merge: backport to 1.3.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 34, 'closed_issues': 19, 'state': 'open', 'created_at': '2021-08-15T08:07:48Z', 'updated_at': '2021-08-25T12:02:39Z', 'due_on': '2021-09-05T07:00:00Z', 'closed_at': None}",2,2021-08-25T10:58:27Z,2021-08-25T12:41:11Z,,NONE,,"- [x ] I have checked that this issue has not already been reported.

- [x ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
import pandas as pd

df = pd.DataFrame([[1, 2, 3, 4, 5, 6]]*3)
df.columns = pd.MultiIndex.from_product([['a', 'b'], ['i', 'j', 'k']])

print('all normal int:')
print(df.groupby(level=1, axis=1).sum())

for col in df.columns:
    if col[-1] == 'j':
        df[col] = df[col].astype('Int64')

print('mixed int:')
print(df.groupby(level=1, axis=1).sum())

for col in df.columns:
    df[col] = df[col].astype('Int64')

print('all nullable int:')
print(df.groupby(level=1, axis=1).sum())

```

#### Problem description

If columns have mixed datatypes, in the example partially normal ints and partially nullable ints, several aggregation methods in the example .sum(), of the DataFrameGroupBy objects unexpectedly return empty DataFrames. This behavior was not yet present in version 1.2.5.

#### Expected Output

Output should be the same for mixed and non mixed

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : c7f7443c1bad8262358114d5e88cd9c8a308e8aa
python           : 3.8.6.final.0
python-bits      : 64
OS               : Linux
OS-release       : 3.10.0-1127.19.1.el7.x86_64
Version          : #1 SMP Tue Aug 11 19:12:04 EDT 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C
LOCALE           : None.None

pandas           : 1.3.1
numpy            : 1.21.1
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.3
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.1.2
blosc            : None
feather          : 0.4.1
xlsxwriter       : 1.4.5
lxml.etree       : 4.6.3
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.2
fsspec           : 2021.07.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.2.0
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 4.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.22
tables           : 3.6.1
tabulate         : None
xarray           : 0.19.0
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.53.1

</details>
",,
4,https://api.github.com/repos/pandas-dev/pandas/issues/43208,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43208/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43208/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43208/events,https://github.com/pandas-dev/pandas/issues/43208,978991057,MDU6SXNzdWU5Nzg5OTEwNTc=,43208,ENH: add converters to Dataframe constructor,"{'login': 'evoludigit', 'id': 36459148, 'node_id': 'MDQ6VXNlcjM2NDU5MTQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/36459148?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/evoludigit', 'html_url': 'https://github.com/evoludigit', 'followers_url': 'https://api.github.com/users/evoludigit/followers', 'following_url': 'https://api.github.com/users/evoludigit/following{/other_user}', 'gists_url': 'https://api.github.com/users/evoludigit/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/evoludigit/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/evoludigit/subscriptions', 'organizations_url': 'https://api.github.com/users/evoludigit/orgs', 'repos_url': 'https://api.github.com/users/evoludigit/repos', 'events_url': 'https://api.github.com/users/evoludigit/events{/privacy}', 'received_events_url': 'https://api.github.com/users/evoludigit/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1465286368, 'node_id': 'MDU6TGFiZWwxNDY1Mjg2MzY4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Constructors', 'name': 'Constructors', 'color': 'd4c5f9', 'default': False, 'description': 'Series/DataFrame/Index/pd.array Constructors'}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}]",open,False,,[],,1,2021-08-25T10:41:32Z,2021-08-25T12:09:40Z,,NONE,,"#### Is your feature request related to a problem?

I am using pandas to read both csv files and lists of lists.

I have a dictionary mapping some colum headers to a conversion function:

`dict_converters = {""column_a"": func_a, ""column_b"": func_b, ""column_e"": func_a} `

I find the converters argument in pandas.read_csv to be very useful to pass a dictionary mapping columns to functions so as to apply a bunch of transformations in a single pass:

`df = pd.read_csv(""data.csv"", converters=dict_converters)`

Doing the same for a dataframe constructed from a list of lists implies to iterate over each transformation:

```
df = pd.DataFrame(data[1:], columns=data[0])
for k, v in dict_converters.items():
    df[k] = df[k].apply(v)

```
#### The solution I would like

It would be nice to be able to use the same syntax as in the read_csv function:
`df = pd.DataFrame(data[1:], columns=data[0], converters=dict_converters)`


#### API breaking implications

Not sure, but as an added feature this should maintain backward compatibility.

#### Example code
[data.csv](https://github.com/pandas-dev/pandas/files/7046279/data.csv)
[converters.py.md](https://github.com/pandas-dev/pandas/files/7046291/converters.py.md)
",,
5,https://api.github.com/repos/pandas-dev/pandas/issues/43207,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43207/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43207/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43207/events,https://github.com/pandas-dev/pandas/pull/43207,978983924,MDExOlB1bGxSZXF1ZXN0NzE5NDcxNDcy,43207,DOC: ecosystem pandas-stubs information,"{'login': 'zkrolikowski-vl', 'id': 63653095, 'node_id': 'MDQ6VXNlcjYzNjUzMDk1', 'avatar_url': 'https://avatars.githubusercontent.com/u/63653095?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zkrolikowski-vl', 'html_url': 'https://github.com/zkrolikowski-vl', 'followers_url': 'https://api.github.com/users/zkrolikowski-vl/followers', 'following_url': 'https://api.github.com/users/zkrolikowski-vl/following{/other_user}', 'gists_url': 'https://api.github.com/users/zkrolikowski-vl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zkrolikowski-vl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zkrolikowski-vl/subscriptions', 'organizations_url': 'https://api.github.com/users/zkrolikowski-vl/orgs', 'repos_url': 'https://api.github.com/users/zkrolikowski-vl/repos', 'events_url': 'https://api.github.com/users/zkrolikowski-vl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zkrolikowski-vl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-25T10:33:03Z,2021-08-25T17:41:58Z,,NONE,,"- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Added information about pandas-stubs to both the .rst and .md ecosystem doc files.

This relates to https://github.com/pandas-dev/pandas/issues/43197",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43207', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43207', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43207.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43207.patch'}"
6,https://api.github.com/repos/pandas-dev/pandas/issues/43206,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43206/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43206/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43206/events,https://github.com/pandas-dev/pandas/issues/43206,978969400,MDU6SXNzdWU5Nzg5Njk0MDA=,43206,BUG: inconsistent `groupby.apply` behaviour depending on column dtypes,"{'login': 'od-crypto', 'id': 67697789, 'node_id': 'MDQ6VXNlcjY3Njk3Nzg5', 'avatar_url': 'https://avatars.githubusercontent.com/u/67697789?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/od-crypto', 'html_url': 'https://github.com/od-crypto', 'followers_url': 'https://api.github.com/users/od-crypto/followers', 'following_url': 'https://api.github.com/users/od-crypto/following{/other_user}', 'gists_url': 'https://api.github.com/users/od-crypto/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/od-crypto/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/od-crypto/subscriptions', 'organizations_url': 'https://api.github.com/users/od-crypto/orgs', 'repos_url': 'https://api.github.com/users/od-crypto/repos', 'events_url': 'https://api.github.com/users/od-crypto/events{/privacy}', 'received_events_url': 'https://api.github.com/users/od-crypto/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/89', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/89', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/89/labels', 'id': 7059576, 'node_id': 'MI_kwDOAA0YD84Aa7h4', 'number': 89, 'title': '1.3.3', 'description': 'on-merge: backport to 1.3.x', 'creator': {'login': 'simonjayhawkins', 'id': 13159005, 'node_id': 'MDQ6VXNlcjEzMTU5MDA1', 'avatar_url': 'https://avatars.githubusercontent.com/u/13159005?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/simonjayhawkins', 'html_url': 'https://github.com/simonjayhawkins', 'followers_url': 'https://api.github.com/users/simonjayhawkins/followers', 'following_url': 'https://api.github.com/users/simonjayhawkins/following{/other_user}', 'gists_url': 'https://api.github.com/users/simonjayhawkins/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/simonjayhawkins/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/simonjayhawkins/subscriptions', 'organizations_url': 'https://api.github.com/users/simonjayhawkins/orgs', 'repos_url': 'https://api.github.com/users/simonjayhawkins/repos', 'events_url': 'https://api.github.com/users/simonjayhawkins/events{/privacy}', 'received_events_url': 'https://api.github.com/users/simonjayhawkins/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 34, 'closed_issues': 19, 'state': 'open', 'created_at': '2021-08-15T08:07:48Z', 'updated_at': '2021-08-25T12:02:39Z', 'due_on': '2021-09-05T07:00:00Z', 'closed_at': None}",4,2021-08-25T10:16:56Z,2021-08-25T17:27:57Z,,NONE,,"I see strange `groupby.apply` behaviour: resulting index depends on the existence of the `Timestamp` dtype column. MWE: 

```python
import pandas as pd
df = pd.DataFrame({
    'date_val': {
        0: pd.Timestamp('2017-01-01 00:00:00'),
        1: pd.Timestamp('2017-01-01 00:00:00'),
        2: pd.Timestamp('2017-02-01 00:00:00'),
        3: pd.Timestamp('2017-02-01 00:00:00')
    },
    'uid': {
        0: '1',
        1: '2',
        2: '1',
        3: '2'
    },
    'str_val': {
        0: str('2017-01-01 00:00:00'),
        1: str('2017-01-01 00:00:00'),
        2: str('2017-02-01 00:00:00'),
        3: str('2017-02-01 00:00:00')
    }
})

df1 = df.groupby('uid', as_index=False)[['uid', 'str_val', 'date_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df2 = df.groupby('uid', as_index=False)[['uid', 'str_val']].apply(lambda x: x.sort_values(by='str_val',ascending=True))
df3 = df.groupby('uid', as_index=False)[['uid', 'date_val']].apply(lambda x: x.sort_values(by='date_val',ascending=True))

print(df1)
print(df2)
print(df3)
```

Output:

```
  uid              str_val   date_val
0   1  2017-01-01 00:00:00 2017-01-01
1   2  2017-01-01 00:00:00 2017-01-01
2   1  2017-02-01 00:00:00 2017-02-01
3   2  2017-02-01 00:00:00 2017-02-01
    uid              str_val
0 0   1  2017-01-01 00:00:00
  2   1  2017-02-01 00:00:00
1 1   2  2017-01-01 00:00:00
  3   2  2017-02-01 00:00:00
  uid   date_val
0   1 2017-01-01
1   2 2017-01-01
2   1 2017-02-01
3   2 2017-02-01
```
I expect the index to be like in the second output (`df2`). Indexes in `df1` and `df3` seem strange.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.0.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 18.7.0
Version          : Darwin Kernel Version 18.7.0: Mon Apr 27 20:09:39 PDT 2020; root:xnu-4903.278.35~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.26.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
",,
7,https://api.github.com/repos/pandas-dev/pandas/issues/43205,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43205/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43205/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43205/events,https://github.com/pandas-dev/pandas/issues/43205,978804183,MDU6SXNzdWU5Nzg4MDQxODM=,43205,Combination of groupby with dropna set to True and apply function not returning expected output,"{'login': 'deponovo', 'id': 45828280, 'node_id': 'MDQ6VXNlcjQ1ODI4Mjgw', 'avatar_url': 'https://avatars.githubusercontent.com/u/45828280?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/deponovo', 'html_url': 'https://github.com/deponovo', 'followers_url': 'https://api.github.com/users/deponovo/followers', 'following_url': 'https://api.github.com/users/deponovo/following{/other_user}', 'gists_url': 'https://api.github.com/users/deponovo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/deponovo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/deponovo/subscriptions', 'organizations_url': 'https://api.github.com/users/deponovo/orgs', 'repos_url': 'https://api.github.com/users/deponovo/repos', 'events_url': 'https://api.github.com/users/deponovo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/deponovo/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}, {'id': 697792067, 'node_id': 'MDU6TGFiZWw2OTc3OTIwNjc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Apply', 'name': 'Apply', 'color': 'fbca04', 'default': False, 'description': 'Apply, Aggregate, Transform'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 1065, 'closed_issues': 764, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2021-08-25T17:55:55Z', 'due_on': None, 'closed_at': None}",1,2021-08-25T07:18:02Z,2021-08-25T15:02:17Z,,NONE,,"(Using pandas 1.3.1 and numpy 1.20.3)

This is a repetition of the SO question found [here](https://stackoverflow.com/questions/68918019/pandas-groupby-with-dropna-set-to-true/68918101?noredirect=1#comment121798992_68918101). (I did not have this issue previously when working with version 1.1.3).

In the following snippet:
```
import pandas as pd
import numpy as np

df = pd.DataFrame(
    {
        ""a"": [1, 2, 3, 4, 5, 6, 7, 8, 9], 
        ""b"": [1, np.nan, 1, np.nan, 2, 1, 2, np.nan, 1]
    }
)
df_again = df.groupby(""b"", dropna=False).apply(lambda x: x)
```
I was expecting df and df_again to be identical. But they are not:
```
df
   a    b
0  1  1.0
1  2  NaN
2  3  1.0
3  4  NaN
4  5  2.0
5  6  1.0
6  7  2.0
7  8  NaN
8  9  1.0

df_again
   a    b
0  1  1.0
2  3  1.0
4  5  2.0
5  6  1.0
6  7  2.0
8  9  1.0
```

Now, if I tweak slightly the lambda expression slightly to ""see"" what is going on by `df.groupby(""b"", dropna=False).apply(lambda x: print(x))` I can actually visualize that also the portion of the `df` where `b` was `NaN` was processed.",,
8,https://api.github.com/repos/pandas-dev/pandas/issues/43203,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43203/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43203/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43203/events,https://github.com/pandas-dev/pandas/pull/43203,978650016,MDExOlB1bGxSZXF1ZXN0NzE5MjA0NzAx,43203,REF: fast_xs avoid object dtype,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-25T02:47:24Z,2021-08-25T02:47:24Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43203', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43203', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43203.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43203.patch'}"
9,https://api.github.com/repos/pandas-dev/pandas/issues/43201,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43201/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43201/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43201/events,https://github.com/pandas-dev/pandas/issues/43201,978304154,MDU6SXNzdWU5NzgzMDQxNTQ=,43201,BUG: exception raised on subclassed DataFrame when calling _dispatch_frame_op,"{'login': 'leobrl', 'id': 566282, 'node_id': 'MDQ6VXNlcjU2NjI4Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/566282?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/leobrl', 'html_url': 'https://github.com/leobrl', 'followers_url': 'https://api.github.com/users/leobrl/followers', 'following_url': 'https://api.github.com/users/leobrl/following{/other_user}', 'gists_url': 'https://api.github.com/users/leobrl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/leobrl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/leobrl/subscriptions', 'organizations_url': 'https://api.github.com/users/leobrl/orgs', 'repos_url': 'https://api.github.com/users/leobrl/repos', 'events_url': 'https://api.github.com/users/leobrl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/leobrl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1539579994, 'node_id': 'MDU6TGFiZWwxNTM5NTc5OTk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/metadata', 'name': 'metadata', 'color': '56efc9', 'default': False, 'description': '_metadata, .attrs'}, {'id': 2559562239, 'node_id': 'MDU6TGFiZWwyNTU5NTYyMjM5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Subclassing', 'name': 'Subclassing', 'color': 'abf98b', 'default': False, 'description': 'Subclassing pandas objects'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 1065, 'closed_issues': 764, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2021-08-25T17:55:55Z', 'due_on': None, 'closed_at': None}",2,2021-08-24T16:59:23Z,2021-08-25T17:22:36Z,,NONE,,"- [ x ] I have checked that this issue has not already been reported.

- [ x ] I have confirmed this bug exists on the latest version of pandas.

- [ x ] (optional) I have confirmed this bug exists on the master branch of pandas.

#### Code Sample, a copy-pastable example

```python
import pandas as pd
import functools

class SubclassedSeries(pd.Series):
    
    @property
    def _constructor(self):
        return SubclassedSeries

    @property
    def _constructor_expanddim(self):
        return SubclassedDataFrame


class SubclassedDataFrame(pd.DataFrame):
    _metadata = ['my_extra_data']
    
    def __init__(self, my_extra_data, *args, **kwargs):
        self.my_extra_data = my_extra_data
        super().__init__(*args, **kwargs)
    
    @property
    def _constructor(self):
        return functools.partial(self.__class__, self.my_extra_data)

    @property
    def _constructor_sliced(self):
        return SubclassedSeries
    
x = SubclassedDataFrame(""some_data"", {""A"":[1,2,3], ""B"":[4,5,6]})
x*2
```

#### Problem description

This code raises an exception, ultimately because function ```_dispatch_frame_op``` in \pandas\core\frame.py returns ```type(self)(bm)```. Shouldn't instead return ```self._constructor(bm)```?

#### Expected Output
```python
	A	B
0	2	8
1	4	10
2	6	12
```
#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.10.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-81-generic
Version          : #91-Ubuntu SMP Thu Jul 15 19:09:17 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.3.2
numpy            : 1.20.1
pytz             : 2019.3
dateutil         : 2.7.3
pip              : 21.0.1
setuptools       : 45.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.3
IPython          : 7.21.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : 1.6.1
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
",,
10,https://api.github.com/repos/pandas-dev/pandas/issues/43200,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43200/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43200/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43200/events,https://github.com/pandas-dev/pandas/pull/43200,978278351,MDExOlB1bGxSZXF1ZXN0NzE4ODk0MTc3,43200,CLN: remove no-longer-used,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-24T16:27:50Z,2021-08-24T16:27:50Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43200', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43200', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43200.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43200.patch'}"
11,https://api.github.com/repos/pandas-dev/pandas/issues/43199,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43199/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43199/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43199/events,https://github.com/pandas-dev/pandas/pull/43199,978115075,MDExOlB1bGxSZXF1ZXN0NzE4NzU4ODk0,43199,BUG: convert_dtypes incorrectly converts byte strings to strings in 1.3+,"{'login': 'shubham11941140', 'id': 63910248, 'node_id': 'MDQ6VXNlcjYzOTEwMjQ4', 'avatar_url': 'https://avatars.githubusercontent.com/u/63910248?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/shubham11941140', 'html_url': 'https://github.com/shubham11941140', 'followers_url': 'https://api.github.com/users/shubham11941140/followers', 'following_url': 'https://api.github.com/users/shubham11941140/following{/other_user}', 'gists_url': 'https://api.github.com/users/shubham11941140/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/shubham11941140/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/shubham11941140/subscriptions', 'organizations_url': 'https://api.github.com/users/shubham11941140/orgs', 'repos_url': 'https://api.github.com/users/shubham11941140/repos', 'events_url': 'https://api.github.com/users/shubham11941140/events{/privacy}', 'received_events_url': 'https://api.github.com/users/shubham11941140/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,11,2021-08-24T13:42:46Z,2021-08-25T13:54:20Z,,NONE,,"- [x] closes #43183
- [x] tests added / passed in the test_convert_dtypes.py file
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

Added extra try except block to identify the correct type to solve the problem.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43199', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43199', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43199.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43199.patch'}"
12,https://api.github.com/repos/pandas-dev/pandas/issues/43198,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43198/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43198/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43198/events,https://github.com/pandas-dev/pandas/issues/43198,978046775,MDU6SXNzdWU5NzgwNDY3NzU=,43198,"BUG: resampling 2D with closed=right fails with ""Values falls before first bin""","{'login': 'batterseapower', 'id': 18488, 'node_id': 'MDQ6VXNlcjE4NDg4', 'avatar_url': 'https://avatars.githubusercontent.com/u/18488?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/batterseapower', 'html_url': 'https://github.com/batterseapower', 'followers_url': 'https://api.github.com/users/batterseapower/followers', 'following_url': 'https://api.github.com/users/batterseapower/following{/other_user}', 'gists_url': 'https://api.github.com/users/batterseapower/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/batterseapower/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/batterseapower/subscriptions', 'organizations_url': 'https://api.github.com/users/batterseapower/orgs', 'repos_url': 'https://api.github.com/users/batterseapower/repos', 'events_url': 'https://api.github.com/users/batterseapower/events{/privacy}', 'received_events_url': 'https://api.github.com/users/batterseapower/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2021-08-24T12:30:26Z,2021-08-24T12:35:26Z,,CONTRIBUTOR,,"- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas. (1.3.1)
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---
#### Code Sample, a copy-pastable example

```python
# ValueError: Values falls before first bin
pd.Series(index=pd.DatetimeIndex(['2013-04-01 22:00:00'])).resample('2D', closed='right').max()

# Works OK
pd.Series(index=pd.DatetimeIndex(['2013-04-01 22:00:00'])).resample('1D', closed='right').max()
pd.Series(index=pd.DatetimeIndex(['2013-04-01 22:00:00'])).resample('2D').max()
```

(Any number of days > 1 shows the same bug)

Stack trace from failure:
<details>

```
ValueError                                Traceback (most recent call last)
<ipython-input-171-dd7aa6747f09> in <module>
----> 1 itensors.unwrap_1d(pd.Series(np.arange(len(de.times)), index=de.times).resample('14D', closed='right', label='right').max())

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in f(self, _method, min_count, *args, **kwargs)
    955     def f(self, _method=method, min_count=0, *args, **kwargs):
    956         nv.validate_resampler_func(_method, args, kwargs)
--> 957         return self._downsample(_method, min_count=min_count)
    958 
    959     f.__doc__ = getattr(GroupBy, method).__doc__

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in _downsample(self, how, **kwargs)
   1051         **kwargs : kw args passed to how function
   1052         """"""
-> 1053         self._set_binner()
   1054         how = self._get_cython_func(how) or how
   1055         ax = self.ax

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in _set_binner(self)
    193         """"""
    194         if self.binner is None:
--> 195             self.binner, self.grouper = self._get_binner()
    196 
    197     def _get_binner(self):

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in _get_binner(self)
    200         has already been called.
    201         """"""
--> 202         binner, bins, binlabels = self._get_binner_for_time()
    203         assert len(bins) == len(binlabels)
    204         bin_grouper = BinGrouper(bins, binlabels, indexer=self.groupby.indexer)

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in _get_binner_for_time(self)
   1040         if self.kind == ""period"":
   1041             return self.groupby._get_time_period_bins(self.ax)
-> 1042         return self.groupby._get_time_bins(self.ax)
   1043 
   1044     def _downsample(self, how, **kwargs):

~\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\resample.py in _get_time_bins(self, ax)
   1526 
   1527         # general version, knowing nothing about relative frequencies
-> 1528         bins = lib.generate_bins_dt64(
   1529             ax_values, bin_edges, self.closed, hasnans=ax.hasnans
   1530         )

pandas\_libs\lib.pyx in pandas._libs.lib.generate_bins_dt64()

ValueError: Values falls before first bin
```

</details>

#### Problem description

If nothing falls exactly on the bin edge, `closed=right` should give exactly the same results as `closed=left`. However, for this example the `closed=right` case just fails even though `closed=left` succeeds.

#### Expected Output

```
2013-04-01   NaN
Freq: D, dtype: float64
```

#### Output of ``pd.show_versions()``

(`pd.show_versions` doesn't work on my 1.3.1 install so this is from a different environment.)

<details>

INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.0
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.18.0
xlrd             : 2.0.1
xlwt             : None
numba            : 0.53.0

</details>
",,
13,https://api.github.com/repos/pandas-dev/pandas/issues/43197,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43197/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43197/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43197/events,https://github.com/pandas-dev/pandas/issues/43197,978002880,MDU6SXNzdWU5NzgwMDI4ODA=,43197,How to make pandas-stubs library compliant with pandas development team requirements,"{'login': 'zkrolikowski-vl', 'id': 63653095, 'node_id': 'MDQ6VXNlcjYzNjUzMDk1', 'avatar_url': 'https://avatars.githubusercontent.com/u/63653095?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/zkrolikowski-vl', 'html_url': 'https://github.com/zkrolikowski-vl', 'followers_url': 'https://api.github.com/users/zkrolikowski-vl/followers', 'following_url': 'https://api.github.com/users/zkrolikowski-vl/following{/other_user}', 'gists_url': 'https://api.github.com/users/zkrolikowski-vl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/zkrolikowski-vl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/zkrolikowski-vl/subscriptions', 'organizations_url': 'https://api.github.com/users/zkrolikowski-vl/orgs', 'repos_url': 'https://api.github.com/users/zkrolikowski-vl/repos', 'events_url': 'https://api.github.com/users/zkrolikowski-vl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/zkrolikowski-vl/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,5,2021-08-24T11:37:36Z,2021-08-25T11:04:17Z,,NONE,,"Hello,

my name is Zbigniew Królikowski. I am a software developer at VirtusLab.

Together with my colleagues we started working on our own [pandas type stubs library](https://github.com/VirtusLab/pandas-stubs), and at some point decided to make it open-source.

We wanted to ask you:
1. Is the separation between our library and pandas itself clear? We wanted to be clear on the authorship so we added a [disclaimer](https://github.com/VirtusLab/pandas-stubs).
2. Do you see any issues with how we promote our library, especially in terms of our graphics?

We'd be very grateful to hear your thoughts on this.

Best regards,
Zbigniew Królikowski",,
14,https://api.github.com/repos/pandas-dev/pandas/issues/43196,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43196/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43196/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43196/events,https://github.com/pandas-dev/pandas/issues/43196,977878073,MDU6SXNzdWU5Nzc4NzgwNzM=,43196,ENH: Change implementation of pandas.api.types.is_list_like to check for iterability in more pythonic way,"{'login': 'dcoukos', 'id': 13315281, 'node_id': 'MDQ6VXNlcjEzMzE1Mjgx', 'avatar_url': 'https://avatars.githubusercontent.com/u/13315281?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/dcoukos', 'html_url': 'https://github.com/dcoukos', 'followers_url': 'https://api.github.com/users/dcoukos/followers', 'following_url': 'https://api.github.com/users/dcoukos/following{/other_user}', 'gists_url': 'https://api.github.com/users/dcoukos/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/dcoukos/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/dcoukos/subscriptions', 'organizations_url': 'https://api.github.com/users/dcoukos/orgs', 'repos_url': 'https://api.github.com/users/dcoukos/repos', 'events_url': 'https://api.github.com/users/dcoukos/events{/privacy}', 'received_events_url': 'https://api.github.com/users/dcoukos/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2021-08-24T09:06:11Z,2021-08-24T09:14:32Z,,NONE,,"#### Is your feature request related to a problem?

Yes, this would improve predictability of behavior with pandas extension arrays.

#### Describe the solution you'd like

`pandas.api.types.is_list_like` can check for iterability in a more pythonic way according to https://docs.python.org/3/glossary.html#term-iterable. This would result in the appropriate call being `iter(obj)` rather than checking for `__iter__` attribute.

#### API breaking implications

This will not affect the API.

#### Describe alternatives you've considered

Alternative solutions include communicating to third parties that they must change their extension arrays to include `hasattr(q, ""__iter__"") == False` to make sure that classes with ambiguous data iterability (may contain either scalar or array-like data) are perceived as utterable when they contain scalar data.

#### Additional context

Opened a bug report for this issue. I think an enhancement request is more appropriate, but I am linking the previous (closed) bug report as it includes useful information.
#43195 

",,
15,https://api.github.com/repos/pandas-dev/pandas/issues/43194,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43194/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43194/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43194/events,https://github.com/pandas-dev/pandas/issues/43194,977730537,MDU6SXNzdWU5Nzc3MzA1Mzc=,43194,Ambiguous behaviour when index is bool type?,"{'login': 'MacroBull', 'id': 2204917, 'node_id': 'MDQ6VXNlcjIyMDQ5MTc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/2204917?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MacroBull', 'html_url': 'https://github.com/MacroBull', 'followers_url': 'https://api.github.com/users/MacroBull/followers', 'following_url': 'https://api.github.com/users/MacroBull/following{/other_user}', 'gists_url': 'https://api.github.com/users/MacroBull/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MacroBull/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MacroBull/subscriptions', 'organizations_url': 'https://api.github.com/users/MacroBull/orgs', 'repos_url': 'https://api.github.com/users/MacroBull/repos', 'events_url': 'https://api.github.com/users/MacroBull/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MacroBull/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,1,2021-08-24T05:51:51Z,2021-08-24T16:22:04Z,,NONE,,"- [x] I have checked that this issue has not already been reported.

- [ ] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python
# Your code here

pandas.Series([True, True, False]).value_counts()[[False]]
```

#### Problem description

[this should explain **why** the current behaviour is a problem and why the expected output is a better solution]

```python
pandas/core/indexers.py in check_array_indexer(array, indexer)
    468         # GH26658
    469         if len(indexer) != len(array):
--> 470             raise IndexError(
    471                 f""Boolean index has wrong length: ""
    472                 f""{len(indexer)} instead of {len(array)}""

IndexError: Boolean index has wrong length: 1 instead of 2
```

It seems that `Series.__getitem__` and `check_bool_indexer` do not work well for bool-typed index

#### Expected Output

```python
<pandas.Series>
False    1
dtype: int64
```

#### Output of ``pd.show_versions()``

<details>

[paste the output of ``pd.show_versions()`` here leaving a blank line after the details tag]

INSTALLED VERSIONS
------------------
commit           : 67a3d4241ab84419856b84fc3ebc9abcbe66c6b3
python           : 3.8.5.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.UTF-8

pandas           : 1.1.4
numpy            : 1.19.1
pytz             : 2020.1
dateutil         : 2.8.1
pip              : 20.2.3
setuptools       : 49.6.0.post20200814
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : 3.2.1
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 2.11.2
IPython          : 7.18.1
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.2
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pytables         : None
pyxlsb           : None
s3fs             : None
scipy            : 1.5.3
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
",,
16,https://api.github.com/repos/pandas-dev/pandas/issues/43193,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43193/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43193/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43193/events,https://github.com/pandas-dev/pandas/pull/43193,977592358,MDExOlB1bGxSZXF1ZXN0NzE4MzE2Mzg2,43193,DOC: OSX -> macOS,"{'login': 'partev', 'id': 23830955, 'node_id': 'MDQ6VXNlcjIzODMwOTU1', 'avatar_url': 'https://avatars.githubusercontent.com/u/23830955?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/partev', 'html_url': 'https://github.com/partev', 'followers_url': 'https://api.github.com/users/partev/followers', 'following_url': 'https://api.github.com/users/partev/following{/other_user}', 'gists_url': 'https://api.github.com/users/partev/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/partev/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/partev/subscriptions', 'organizations_url': 'https://api.github.com/users/partev/orgs', 'repos_url': 'https://api.github.com/users/partev/repos', 'events_url': 'https://api.github.com/users/partev/events{/privacy}', 'received_events_url': 'https://api.github.com/users/partev/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 63, 'closed_issues': 418, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-08-25T17:55:56Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",3,2021-08-24T00:41:52Z,2021-08-25T16:37:34Z,,CONTRIBUTOR,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43193', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43193', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43193.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43193.patch'}"
17,https://api.github.com/repos/pandas-dev/pandas/issues/43191,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43191/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43191/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43191/events,https://github.com/pandas-dev/pandas/pull/43191,977563107,MDExOlB1bGxSZXF1ZXN0NzE4MjkxNDEy,43191,DEPS: bump sqlalchemy min support version to 1.4.0,"{'login': 'fangchenli', 'id': 7614606, 'node_id': 'MDQ6VXNlcjc2MTQ2MDY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7614606?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/fangchenli', 'html_url': 'https://github.com/fangchenli', 'followers_url': 'https://api.github.com/users/fangchenli/followers', 'following_url': 'https://api.github.com/users/fangchenli/following{/other_user}', 'gists_url': 'https://api.github.com/users/fangchenli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/fangchenli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/fangchenli/subscriptions', 'organizations_url': 'https://api.github.com/users/fangchenli/orgs', 'repos_url': 'https://api.github.com/users/fangchenli/repos', 'events_url': 'https://api.github.com/users/fangchenli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/fangchenli/received_events', 'type': 'User', 'site_admin': False}","[{'id': 527603109, 'node_id': 'MDU6TGFiZWw1Mjc2MDMxMDk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dependencies', 'name': 'Dependencies', 'color': 'd93f0b', 'default': False, 'description': 'Required and optional dependencies'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/86', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/86/labels', 'id': 6840253, 'node_id': 'MDk6TWlsZXN0b25lNjg0MDI1Mw==', 'number': 86, 'title': '1.4', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 63, 'closed_issues': 418, 'state': 'open', 'created_at': '2021-06-09T18:28:42Z', 'updated_at': '2021-08-25T17:55:56Z', 'due_on': '2021-12-31T08:00:00Z', 'closed_at': None}",1,2021-08-23T23:31:42Z,2021-08-25T17:11:34Z,,MEMBER,,"precursor of #42976
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43191', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43191', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43191.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43191.patch'}"
18,https://api.github.com/repos/pandas-dev/pandas/issues/43190,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43190/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43190/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43190/events,https://github.com/pandas-dev/pandas/issues/43190,977548945,MDU6SXNzdWU5Nzc1NDg5NDU=,43190,BUG: infinite recursion when using `np.fmin` to combine > 2 Series/DataFrames elementwise,"{'login': 'batterseapower', 'id': 18488, 'node_id': 'MDQ6VXNlcjE4NDg4', 'avatar_url': 'https://avatars.githubusercontent.com/u/18488?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/batterseapower', 'html_url': 'https://github.com/batterseapower', 'followers_url': 'https://api.github.com/users/batterseapower/followers', 'following_url': 'https://api.github.com/users/batterseapower/following{/other_user}', 'gists_url': 'https://api.github.com/users/batterseapower/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/batterseapower/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/batterseapower/subscriptions', 'organizations_url': 'https://api.github.com/users/batterseapower/orgs', 'repos_url': 'https://api.github.com/users/batterseapower/repos', 'events_url': 'https://api.github.com/users/batterseapower/events{/privacy}', 'received_events_url': 'https://api.github.com/users/batterseapower/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,2,2021-08-23T23:03:30Z,2021-08-24T15:21:54Z,,CONTRIBUTOR,,"- [x] I have checked that this issue has not already been reported.
- [x] I have confirmed this bug exists on the latest version of pandas (1.3.1)
- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

#### Code Sample, a copy-pastable example

```python
# These 2-adic invocations don't fail and return a Series/DataFrame/ndarray respectively:
np.fmin(pd.Series(np.array([1, 2])), pd.Series(np.array([3, 4])))
np.fmin(pd.DataFrame(np.array([[1, 2]])), pd.DataFrame(np.array([[3, 4]])))
np.fmin(np.array([1, 2]), np.array([3, 4]), np.array([5, 6]))

# These 3-adic invocations fail (RecursionError: maximum recursion depth exceeded)
np.fmin(pd.Series(np.array([1, 2])), pd.Series(np.array([3, 4])), pd.Series(np.array([5, 6])))
np.minimum(pd.Series(np.array([1, 2])), pd.Series(np.array([3, 4])), pd.Series(np.array([5, 6])))
np.fmin(pd.DataFrame(np.array([[1, 2]])), pd.DataFrame(np.array([[3, 4]])), pd.DataFrame(np.array([[5, 6]])))
```

#### Problem description

I'm not sure if this is strictly a Pandas bug since it involves a Numpy function, but the infinite recursion goes through Pandas functions only so it seems like the only place it could be solved is within Pandas itself.

The end of the stack trace looks like this:

```
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\generic.py"", line 1936, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\arraylike.py"", line 358, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\generic.py"", line 1936, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\arraylike.py"", line 358, in array_ufunc
    result = getattr(ufunc, method)(*inputs, **kwargs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\generic.py"", line 1936, in __array_ufunc__
    return arraylike.array_ufunc(self, ufunc, method, *inputs, **kwargs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\arraylike.py"", line 357, in array_ufunc
    inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\arraylike.py"", line 357, in <genexpr>
    inputs = tuple(extract_array(x, extract_numpy=True) for x in inputs)
  File ""C:\Users\mboling\Anaconda3\envs\py3_2\lib\site-packages\pandas\core\construction.py"", line 396, in extract_array
    if isinstance(obj, (ABCIndexClass, ABCSeries)):
```

(This RecursionError actually manifested as a segfault in my application so was a bit of a pain to track down.)

#### Expected Output

The failing examples involving `Series` should evaluate to `pd.Series([1, 2])`

#### Output of ``pd.show_versions()``

<details>
INSTALLED VERSIONS
------------------
commit           : 2cb96529396d93b46abab7bbc73a208e708c642e
python           : 3.8.10.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.18363
machine          : AMD64
processor        : Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_United Kingdom.1252

pandas           : 1.2.4
numpy            : 1.20.2
pytz             : 2021.1
dateutil         : 2.8.1
pip              : 21.1.1
setuptools       : 52.0.0.post20210125
Cython           : 0.29.23
pytest           : 6.2.3
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : None
jinja2           : 3.0.0
IPython          : 7.22.0
pandas_datareader: None
bs4              : 4.9.3
bottleneck       : 1.3.2
fsspec           : 0.9.0
fastparquet      : None
gcsfs            : None
matplotlib       : 3.3.4
numexpr          : None
odfpy            : None
openpyxl         : 3.0.7
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.6.2
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : 0.18.0
xlrd             : 2.0.1
xlwt             : None
numba            : 0.53.0
</details>
",,
19,https://api.github.com/repos/pandas-dev/pandas/issues/43189,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43189/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43189/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43189/events,https://github.com/pandas-dev/pandas/pull/43189,977545891,MDExOlB1bGxSZXF1ZXN0NzE4Mjc2MTg2,43189,REF: remove libreduction.SeriesBinGrouper,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T22:57:59Z,2021-08-23T22:58:29Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

xref #40263",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43189', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43189', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43189.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43189.patch'}"
20,https://api.github.com/repos/pandas-dev/pandas/issues/43188,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43188/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43188/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43188/events,https://github.com/pandas-dev/pandas/pull/43188,977539476,MDExOlB1bGxSZXF1ZXN0NzE4MjcxMTA3,43188,BUG: pickle Index[object] preserve dtype,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T22:43:52Z,2021-08-23T22:44:21Z,,MEMBER,,"- [ ] closes #xxxx
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [x] whatsnew entry

xref #43155",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43188', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43188', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43188.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43188.patch'}"
21,https://api.github.com/repos/pandas-dev/pandas/issues/43187,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43187/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43187/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43187/events,https://github.com/pandas-dev/pandas/pull/43187,977465688,MDExOlB1bGxSZXF1ZXN0NzE4MjA2Mzcz,43187,TST: Test renaming a multiindex with duplicates (GH 38015),"{'login': 'andrewwoood', 'id': 23269446, 'node_id': 'MDQ6VXNlcjIzMjY5NDQ2', 'avatar_url': 'https://avatars.githubusercontent.com/u/23269446?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/andrewwoood', 'html_url': 'https://github.com/andrewwoood', 'followers_url': 'https://api.github.com/users/andrewwoood/followers', 'following_url': 'https://api.github.com/users/andrewwoood/following{/other_user}', 'gists_url': 'https://api.github.com/users/andrewwoood/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/andrewwoood/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/andrewwoood/subscriptions', 'organizations_url': 'https://api.github.com/users/andrewwoood/orgs', 'repos_url': 'https://api.github.com/users/andrewwoood/repos', 'events_url': 'https://api.github.com/users/andrewwoood/events{/privacy}', 'received_events_url': 'https://api.github.com/users/andrewwoood/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2021-08-23T21:10:15Z,2021-08-24T17:09:54Z,,CONTRIBUTOR,,"- [x] closes #38015
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry

This is my first real contribution, I appreciate the feedback!",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43187', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43187', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43187.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43187.patch'}"
22,https://api.github.com/repos/pandas-dev/pandas/issues/43186,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43186/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43186/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43186/events,https://github.com/pandas-dev/pandas/pull/43186,977238704,MDExOlB1bGxSZXF1ZXN0NzE4MDA5NDUy,43186,"CLN: tests, annotations","{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean', 'name': 'Clean', 'color': '207de5', 'default': False, 'description': None}]",open,False,,[],,0,2021-08-23T17:03:28Z,2021-08-25T17:01:23Z,,MEMBER,,"- [ ] closes #xxxx
- [ ] tests added / passed
- [ ] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them
- [ ] whatsnew entry
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43186', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43186', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43186.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43186.patch'}"
23,https://api.github.com/repos/pandas-dev/pandas/issues/43185,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43185/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43185/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43185/events,https://github.com/pandas-dev/pandas/pull/43185,977233100,MDExOlB1bGxSZXF1ZXN0NzE4MDA0Njkx,43185,PERF: copy blklocs/blknos in BlockManager.apply,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T16:56:17Z,2021-08-24T16:40:22Z,,MEMBER,,"Avoids a call to _rebuild_blknos_and_blklocs, which in e.g. time_reset_datetimeindex is 34 microseconds",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43185', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43185', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43185.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43185.patch'}"
24,https://api.github.com/repos/pandas-dev/pandas/issues/43184,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43184/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43184/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43184/events,https://github.com/pandas-dev/pandas/pull/43184,977230082,MDExOlB1bGxSZXF1ZXN0NzE4MDAyMDc5,43184,TST: MultiIndex with complex,"{'login': 'debnathshoham', 'id': 6472290, 'node_id': 'MDQ6VXNlcjY0NzIyOTA=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6472290?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/debnathshoham', 'html_url': 'https://github.com/debnathshoham', 'followers_url': 'https://api.github.com/users/debnathshoham/followers', 'following_url': 'https://api.github.com/users/debnathshoham/following{/other_user}', 'gists_url': 'https://api.github.com/users/debnathshoham/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/debnathshoham/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/debnathshoham/subscriptions', 'organizations_url': 'https://api.github.com/users/debnathshoham/orgs', 'repos_url': 'https://api.github.com/users/debnathshoham/repos', 'events_url': 'https://api.github.com/users/debnathshoham/events{/privacy}', 'received_events_url': 'https://api.github.com/users/debnathshoham/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T16:52:36Z,2021-08-24T10:33:22Z,,CONTRIBUTOR,,"- [x] closes #42145 
- [x] tests added / passed
- [x] Ensure all linting tests pass, see [here](https://pandas.pydata.org/pandas-docs/dev/development/contributing.html#code-standards) for how to run them

This has been resolved in the master. I think adding a test will close it.",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43184', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43184', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43184.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43184.patch'}"
25,https://api.github.com/repos/pandas-dev/pandas/issues/43183,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43183/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43183/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43183/events,https://github.com/pandas-dev/pandas/issues/43183,977159341,MDU6SXNzdWU5NzcxNTkzNDE=,43183,BUG: convert_dtypes incorrectly converts byte strings to strings in 1.3+,"{'login': 'nwilliams-lw', 'id': 80686372, 'node_id': 'MDQ6VXNlcjgwNjg2Mzcy', 'avatar_url': 'https://avatars.githubusercontent.com/u/80686372?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/nwilliams-lw', 'html_url': 'https://github.com/nwilliams-lw', 'followers_url': 'https://api.github.com/users/nwilliams-lw/followers', 'following_url': 'https://api.github.com/users/nwilliams-lw/following{/other_user}', 'gists_url': 'https://api.github.com/users/nwilliams-lw/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/nwilliams-lw/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/nwilliams-lw/subscriptions', 'organizations_url': 'https://api.github.com/users/nwilliams-lw/orgs', 'repos_url': 'https://api.github.com/users/nwilliams-lw/repos', 'events_url': 'https://api.github.com/users/nwilliams-lw/events{/privacy}', 'received_events_url': 'https://api.github.com/users/nwilliams-lw/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 31404521, 'node_id': 'MDU6TGFiZWwzMTQwNDUyMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Dtype%20Conversions', 'name': 'Dtype Conversions', 'color': 'e102d8', 'default': False, 'description': 'Unexpected or buggy dtype conversions'}, {'id': 32815646, 'node_id': 'MDU6TGFiZWwzMjgxNTY0Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Regression', 'name': 'Regression', 'color': 'e11d21', 'default': False, 'description': 'Functionality that used to work in a prior pandas version'}]",open,False,,[],,8,2021-08-23T15:30:56Z,2021-08-24T13:38:56Z,,NONE,,"#### Code Sample, a copy-pastable example

This test will pass on pandas 1.2.5 but fail on 1.3 onwards (checked 1.3, 1.3.2). 
```python
def test_convert_dtypes_on_byte_string():
    byte_str = b'binary-string'
    dataframe = pd.DataFrame(
        data={
            ""data"": byte_str,
        },
        index=[0]
    )
    converted_dtypes = dataframe.convert_dtypes()
    assert converted_dtypes['data'][0].decode('ascii') == ""binary-string""
```

#### Problem description

Error on 1.3 onwards:
```
Traceback (most recent call last):
  File ""<stdin>"", line 1, in <module>
  File ""<stdin>"", line 10, in test_convert_dtypes_on_byte_string
AttributeError: 'str' object has no attribute 'decode'
```

The issue is that converted_dtypes() will convert the `data` column values to the string `b'binary-data'`, almost like it has had `str(val)` called on it. On 1.2.5 it is left correctly as a byte array.
 
#### Expected Output

Test should pass. Byte strings should not be converted to string.

#### Output of ``pd.show_versions()``

<details>

INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.11.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Wed Jun 23 00:26:31 PDT 2021; root:xnu-7195.141.2~5/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_GB.UTF-8
LOCALE           : en_GB.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.1.3
setuptools       : 57.4.0
Cython           : None
pytest           : 6.2.4
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : 2.9.1 (dt dec pq3 ext lo64)
jinja2           : 3.0.1
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : 2021.07.0
fastparquet      : 0.7.0
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : 2021.07.0
scipy            : None
sqlalchemy       : 1.4.23
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
",,
26,https://api.github.com/repos/pandas-dev/pandas/issues/43182,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43182/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43182/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43182/events,https://github.com/pandas-dev/pandas/pull/43182,977139966,MDExOlB1bGxSZXF1ZXN0NzE3OTI1OTkx,43182,REF: implement IntervalIndex._get_indexer_unique_sides,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T15:10:35Z,2021-08-23T15:10:35Z,,MEMBER,,Follow-up cleanup to get_indexer work,,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43182', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43182', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43182.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43182.patch'}"
27,https://api.github.com/repos/pandas-dev/pandas/issues/43180,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43180/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43180/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43180/events,https://github.com/pandas-dev/pandas/pull/43180,977045279,MDExOlB1bGxSZXF1ZXN0NzE3ODQ1MDg2,43180,WIP: ENH: `styler.render.repr` option to allow latex repr,"{'login': 'attack68', 'id': 24256554, 'node_id': 'MDQ6VXNlcjI0MjU2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/attack68', 'html_url': 'https://github.com/attack68', 'followers_url': 'https://api.github.com/users/attack68/followers', 'following_url': 'https://api.github.com/users/attack68/following{/other_user}', 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions', 'organizations_url': 'https://api.github.com/users/attack68/orgs', 'repos_url': 'https://api.github.com/users/attack68/repos', 'events_url': 'https://api.github.com/users/attack68/events{/privacy}', 'received_events_url': 'https://api.github.com/users/attack68/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T13:35:35Z,2021-08-23T13:35:35Z,,CONTRIBUTOR,,"adds items to #41395.

also closes #39911 (technically after DataFrame.to_html is deprecated)
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43180', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43180', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43180.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43180.patch'}"
28,https://api.github.com/repos/pandas-dev/pandas/issues/43178,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43178/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43178/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43178/events,https://github.com/pandas-dev/pandas/issues/43178,977036305,MDU6SXNzdWU5NzcwMzYzMDU=,43178,BUG: Series inconsistent with overflow errors in Timedelta calcs,"{'login': 'venaturum', 'id': 51399800, 'node_id': 'MDQ6VXNlcjUxMzk5ODAw', 'avatar_url': 'https://avatars.githubusercontent.com/u/51399800?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/venaturum', 'html_url': 'https://github.com/venaturum', 'followers_url': 'https://api.github.com/users/venaturum/followers', 'following_url': 'https://api.github.com/users/venaturum/following{/other_user}', 'gists_url': 'https://api.github.com/users/venaturum/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/venaturum/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/venaturum/subscriptions', 'organizations_url': 'https://api.github.com/users/venaturum/orgs', 'repos_url': 'https://api.github.com/users/venaturum/repos', 'events_url': 'https://api.github.com/users/venaturum/events{/privacy}', 'received_events_url': 'https://api.github.com/users/venaturum/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,4,2021-08-23T13:26:13Z,2021-08-23T23:32:07Z,,CONTRIBUTOR,,"- [x] I have checked that this issue has not already been reported.

- [x] I have confirmed this bug exists on the latest version of pandas.

- [ ] (optional) I have confirmed this bug exists on the master branch of pandas.

---

**Note**: Please read [this guide](https://matthewrocklin.com/blog/work/2018/02/28/minimal-bug-reports) detailing how to provide the necessary information for us to reproduce your bug.

#### Code Sample, a copy-pastable example

```python

>>> x = pd.Series([pd.Timedelta(100000, ""days""), pd.Timedelta(100000, ""days"")])

# Results in ValueError
>>> x.sum()

# Results in OverflowError
>>> pd.Timedelta(100000, ""days"")*2

# Results in OverflowError
>>> x + x

# Permits overflow
>>> x*2
0   -13504 days +00:25:26.290448384
1   -13504 days +00:25:26.290448384
dtype: timedelta64[ns]
```

#### Problem description

It would seem that pandas.Series calcs with Timedeltas are inconsistent in raising overflow errors, or not.
The exact error is also inconsistent (OverflowError vs ValueError).

#### Expected Output

Ideally `x*2` in above example raises an error, and all overflow related errors are of type OverflowError.

#### Output of ``pd.show_versions()``
INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.7.5.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19041
machine          : AMD64
processor        : Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : None.None

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 19.2.3
setuptools       : 41.2.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
",,
29,https://api.github.com/repos/pandas-dev/pandas/issues/43177,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/43177/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/43177/comments,https://api.github.com/repos/pandas-dev/pandas/issues/43177/events,https://github.com/pandas-dev/pandas/pull/43177,977032017,MDExOlB1bGxSZXF1ZXN0NzE3ODMzNTU5,43177,WIP: ENH: `styler.render.encoding` option,"{'login': 'attack68', 'id': 24256554, 'node_id': 'MDQ6VXNlcjI0MjU2NTU0', 'avatar_url': 'https://avatars.githubusercontent.com/u/24256554?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/attack68', 'html_url': 'https://github.com/attack68', 'followers_url': 'https://api.github.com/users/attack68/followers', 'following_url': 'https://api.github.com/users/attack68/following{/other_user}', 'gists_url': 'https://api.github.com/users/attack68/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/attack68/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/attack68/subscriptions', 'organizations_url': 'https://api.github.com/users/attack68/orgs', 'repos_url': 'https://api.github.com/users/attack68/repos', 'events_url': 'https://api.github.com/users/attack68/events{/privacy}', 'received_events_url': 'https://api.github.com/users/attack68/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2021-08-23T13:23:45Z,2021-08-23T13:23:45Z,,CONTRIBUTOR,,"This pandas option is added to allow the `Styler` options to be independent from the others. See #41395
",,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/43177', 'html_url': 'https://github.com/pandas-dev/pandas/pull/43177', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/43177.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/43177.patch'}"
